botfront/rasa-webchat

- README.md
- Based on issue https://github.com/mrbot-ai/rasa-webchat/issues/42
- Added simple manual how to use customData in Rasa Core. 
> Added customData manual to README.

- CHANGELOG.md
- README.md
- dev/src/index.html
- index.js
- package-lock.json
- package.json
- src/components/Widget/components/Conversation/components/Messages/components/Message/index.js
- src/components/Widget/components/Conversation/components/Messages/components/docViewer/index.js
- src/components/Widget/components/Conversation/components/Messages/components/docViewer/style.scss
- src/index.js
- src/store/reducers/behaviorReducer.js
- src/store/store.js
- src/utils/portal.js
- added a docViewer to view links in a popup
> Doc viewer

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/components/Widget/components/Conversation/components/Messages/components/Message/index.js
- src/components/Widget/components/Conversation/components/Messages/components/docViewer/index.js
- fixed a bug where named links would not render the name
> Fix named links markdown

- CHANGELOG.md
- src/components/Widget/index.js
- src/index.js
- Fixed a bug where the connection would not close down when the component unmounted and continued polling indefinitely in the background.
> fixed connection leak when closing down component

- package-lock.json
- package.json
- update node-sass version to support node12
> fix: update node-sass version to support node12

- commitlint.config.js
- package-lock.json
- package.json
- add commitlint and a husky hook
> feat: add commitlint and husky

- package-lock.json
- package.json
> feat: add standard version

- src/socket-sockjs.js
- allow to pass message.reason in sockjs implementation on LEAVE messages.
> SocketJS LEAVE reason

- src/components/Widget/index.js
- src/components/Widget/test/metadataBehavior.test.js
- src/index.js
> refactor: add default highlighting css

- src/components/Widget/index.js
> refactor: allow differents session confirm arguments (object or string)

- src/components/Widget/components/Launcher/index.js
- src/components/Widget/components/Launcher/style.scss
add support of markdown in the tooltip
> refactor: support for markdown in the tooltip

- src/components/Widget/style.scss
use the user agent p styling from chrome
> refactor: set a default p margin within the widget

- dev/src/index.html
- index.js
- src/components/Widget/index.js
- src/components/Widget/test/metadataBehavior.test.js
- src/index.js
props were not taken a the top level,
rename animation
> fix: default css animations

- src/components/Widget/index.js
support selector matching multiple elements for dom highlight metadata
> refactor: support multiple element for domHighlight metadata

- src/socket-sockjs.js
- The SockJS transport can now receive multiple messages at once 
> feat(): sockjs transport can receive multiple messages at once

- src/components/Widget/test/metadataBehavior.test.js
queryselector instead of queryselectorall was used
> refactor: some tests were using wrong mock

- src/components/Widget/index.js
- src/index.js
- src/store/store.js
removed a possible race condition on session_confirm, session confirm events on onSocketEvent prop were called before the actual one
> fix: removed session_confirm race condition

- src/components/Widget/index.js
- removes message delay for tooltips
> refactor: removes delay for tooltips

- src/components/Widget/components/Conversation/components/Header/style.scss
- src/components/Widget/components/Conversation/components/Messages/components/Message/styles.scss
- src/components/Widget/components/Conversation/components/Messages/components/Snippet/styles.scss
- src/components/Widget/components/Conversation/components/Sender/style.scss
- src/components/Widget/components/Launcher/style.scss
- src/scss/common.scss
> style: new font

- src/components/Widget/components/Launcher/style.scss
> style: launcher color

- src/components/Widget/index.js
- display the highlight after the delay
> refactor: display highlight after the message is shown

- src/components/Widget/components/Conversation/components/Messages/components/QuickReply/index.js
- src/components/Widget/components/Launcher/index.js
> refactor: click on replies buttons in tooltip do not open the webchat

- dev/src/index.html
- src/components/Widget/components/Launcher/style.scss
- src/components/Widget/index.js
- src/components/Widget/style.scss
Automatically scroll to highlights. Always on mobile and only if not in viewport on desktop.
Aslo improves the css for the tooltip on mobiles
> feat: automatically scroll to highlights

- index.js
- src/store/actions/dispatcher.js
- src/store/actions/index.js
- src/store/reducers/behaviorReducer.js
Export the function `toggleInputDisabled` for consumption and allow passing a boolean to toggle on/off the input field.
> feat: allow disabling/enabling input

- src/components/Widget/components/Conversation/components/Messages/components/QuickReply/styles.scss
- src/components/Widget/components/Launcher/style.scss
- list were not displaying properly in the embedded webchat
> fix: stying issues when embedded

- package-lock.json
- package.json
- src/components/Widget/components/Conversation/components/Messages/components/Buttons/index.js
- src/components/Widget/components/Conversation/components/Messages/components/Message/index.js
- src/components/Widget/components/Launcher/index.js
- src/components/Widget/components/Launcher/style.scss
- test-setup.js
- webpack.dev.js
- webpack.prod.js
When you receive multiple messages in a sequence and want to display them in the tooltip, now it displays a sequence with a slider.
> feat: tooltip sequences
