botfront/rasa-webchat

src/components/Widget/components/Conversation/components/Messages/styles.scss
Could not see sender component when widget was embedded in Botfront under Firefox Quantum 60.7.0esr.
=> Fix sender component overflow

README.md, src/components/Widget/components/Conversation/components/Messages/index.js, src/components/Widget/components/Conversation/components/Messages/test/index.test.js, src/components/Widget/components/Conversation/index.js, src/components/Widget/components/Launcher/test/index.test.js, src/components/Widget/index.js, src/components/Widget/layout.js, src/index.js
Rasa lets you send custom data to clients. This change lets you specify a custom component to handle the custom data.
[This rasa community thread](https://forum.rasa.com/t/sending-custom-json-payload-from-actions-workaround-for-utter-custom-message/9139) demonstrates the want for this feature and mentions that rasa-webchat did not support this.
=> [Feature] Add option to use custom component on unknown incoming message data

cloudbuild.yaml, package-lock.json, package.json, src/components/Widget/components/Conversation/components/Messages/components/QuickReply/index.js, src/components/Widget/components/Conversation/components/Messages/components/QuickReply/test/index.test.js, src/components/Widget/components/Conversation/components/Messages/test/index.test.js
- add support of web_url types in quick replies
rely on this PR :  https://github.com/botfront/rasa-addons/pull/48
test: should render a quick reply with a link to google
=> feat: support web url in quick replies

src/components/Widget/index.js
=> fix: cast messages text into string to prevent crashes

src/components/Widget/components/Conversation/components/Messages/components/Message/styles.scss
- Add a margin to the bottom of <p> tags that are not the last element of their parent. this better shows new lines that use the markdown format "{2 spaces}\n"
=> feat: add margin to <p> to display newline

src/socket-sockjs.js
- use message.content instead of .reason to be complient with stompJS
=> fix: disconnect reason through message.content

README.md
Fix botfront.io bad URL
- fix type in botfront.io URL in the readme, previously it's being redirected to botront.io instead of botfront.io
=> Fix botfront.io bad url

README.md, index.js, src/index.js, src/store/reducers/behaviorReducer.js, src/store/store.js
- add widget event callback.. allows for DTM ( tagging ) or simply capture user's interactions with the widget.
=> feat: add widget event callback

src/components/Widget/components/Conversation/components/Messages/components/QuickReply/index.js, src/components/Widget/components/Conversation/components/Messages/components/QuickReply/test/index.test.js, src/components/Widget/test/metadataLinkTarget.test.js
following the update of rasa addons use the field url for   quick replies of type weburl
=> refactor: change field name for the url in quickreplies

src/components/Widget/test/metadataBehavior.test.js, src/store/store.js
the query string is ignored only when is not precised in the callback url
also update the tests
- ...
=> refactor: ignore protocol, host, port and query string in url checking

src/components/Widget/components/Conversation/components/Messages/components/QuickReply/index.js, src/store/reducers/helper.js
quick relies were not displayed correctly after refresh
after a pull of the session they were comming back as a Immutable object
=> fix: quick replies after refresh

src/components/Widget/components/Conversation/components/Messages/components/QuickReply/index.js
correct behavior when the metadata is empty for quick replies, open the link in a new tab
=> refactor: add a default value for links targets

src/components/Widget/index.js
now check if the selector matched an element before trying to change style
- ...
=> fix: crash when trying to hightlight with bad selector

src/socket-sockjs.js, src/socket.js
- The SESSION_CONFIRM message on the SockJS driver can now contain props, and more closely mimics the Socket.io implementation
=> feat(sockjs): session_confirm can contain props

src/components/Widget/index.js
fix duplicate message appearing when closing the chat window
=> fix: message duplicate appearing as a tooltip when closing the chat

src/components/Widget/index.js
Re-read `session_id` from local storage on socket `connect` and `session_confirm` to allow re-use of session. 
Before, the `session_id` was only read on widget initialization which means if the connection was lost and then re-established without re-initializing the component the `session_id`, wasn't reused.
=> fix: allow session re-use by re-reading session_id from local storage

src/components/Widget/components/Conversation/components/Header/style.scss, src/components/Widget/components/Launcher/index.js
- closing the widget one in full screen broke the launcher styles
- there was a margin a the bottom when the widget was full screeen
=> fix: styles when widget is full screen

src/components/Widget/components/Conversation/components/Messages/components/Carousel/styles.scss
- carrousel have a min height
- they can grow relatively to the subtible text
- all card have the height of the biggest one
fix : https://app.asana.com/0/1172906309462386/1175520137156625?utm_term=button&utm_source=Iterable&utm_medium=email&utm_campaign=fr_welcome
=> refactor: carrousel card now have the height of the biggest one

src/components/Widget/components/Conversation/components/Sender/index.js
add { cancelable: true } to the submit event
chrome does not care about cancelable to cancel an event, firefox does
=> fix: page refresh when pressing on enter on firefox

README.md
remplace google storage link with jsDelivr link
=> docs: replace google storage link with jsDelivr link

CONTRIBUTING.md
- The default folder name in the installation step of the `contributing.md` file is wrong. When cloning the project the default project folder name is `rasa-webchat`
=> fix contibuting project folder name

src/components/Widget/components/Launcher/index.js, src/components/Widget/index.js, src/components/Widget/test/metadataStore.test.js, src/utils/dom.js
support a new metadata that allow for a payload to be sent when the tooltip is closed
goes with : https://github.com/botfront/botfront-ee/pull/193
=> feat: possibility to send a payload on tooltip close
